<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace Moodle\Composer\Scaffold\Scaffolding\Generator;

use Composer\Util\Filesystem;

/**
 * Moodle Shim Config File Generator.
 */
class ShimConfigFile extends BaseGenerator
{
    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function generate(): void
    {
        $this->io->write("- <info>Generating Moodle configuration shim file...</info>");

        $targetPath = $this->getMoodlePath() . '/config.php';

        $configContent = $this->getTemplateContent();
        if (Filesystem::isReadable($targetPath)) {
            if (file_get_contents($targetPath) === $configContent) {
                $this->io->write("    <comment>Skipped, file is up to date</comment>");
                return;
            } else {
                if ($this->io->isInteractive()) {
                    $confirm = $this->io->askConfirmation(
                        "    <question>The config.php file already exists and differs from the generated one. Overwrite it? (y/n) </question>",
                        false
                    );
                    if (!$confirm) {
                        $this->io->write("        <comment>Skipped: user chose not to overwrite</comment>");
                        return;
                    }
                }

                $backupFilename = 'config-' . date('Ymd-His') . '.php';
                $filesystem = new Filesystem();
                $filesystem->safeCopy($targetPath, $this->getMoodlePath() . '/' . $backupFilename);
                $this->io->write("        <comment>Backed up existing config.php to {$backupFilename}</comment>");
            }
        }


        file_put_contents($targetPath, $configContent);

        $this->io->write("    <info>Moodle configuration shim file generated.</info>");
    }

    protected function getTemplateContent(): string
    {
        $filesystem = new Filesystem();

        if ($filesystem->isSymlinkedDirectory($this->getMoodlePath())) {
            $installRoot = sprintf("'%s'", $this->getRootPackagePath());
        } else {
            $generatedConfigPath = $this->getMoodlePath() . '/config.php';
            $installRoot = $this->calculateRelativePath(
                $generatedConfigPath,
                $this->getRootPackagePath(),
            );
            $installRoot = sprintf("__DIR__ . '/%s'", $installRoot);
        }

        return <<<TEMPLATE
        <?php

        /**
         * Include the Moodle configuration file for a Composer-based Moodle installation.
         *
         * This file was automatically generated by the Moodle Composer Scaffold plugin.
         *
         * Do NOT edit this file manually. It will be overridden on the next scaffolding operation.
         */

        \$installRoot = {$installRoot};
        \$result = require_once(\$installRoot . '/config.php');
        require_once(\$installRoot . '/vendor/autoload.php');
        require_once(__DIR__ . '/public/lib/setup.php');

        return \$result;

        TEMPLATE;
    }
}
