<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace Moodle\Composer\Scaffold\Scaffolding\Generator;

use Composer\Util\Filesystem;

/**
 * Moodle Composer Autoload Bridge for Composer-installed sites.
 */
class ShimComposerAutoloadFile extends BaseGenerator
{
    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function generate(): void
    {
        $this->io->write("- <info>Generating Moodle Composer Autoloader shim bridge...</info>");

        file_put_contents(
            $this->getMoodlePath() . '/autoload-composer.php',
            $this->getTemplateContent(),
        );

        $this->io->write("    <info>Moodle Composer Autoloader shim bridge generated.</info>");
    }

    protected function getTemplateContent(): string
    {
        $filesystem = new Filesystem();

        if ($filesystem->isSymlinkedDirectory($this->getMoodlePath())) {
            $installRoot = sprintf("'%s'", $this->getRootPackagePath());
        } else {
            $generatedConfigPath = $this->getMoodlePath() . '/config.php';
            $installRoot = $this->calculateRelativePath(
                $generatedConfigPath,
                $this->getRootPackagePath(),
            );
            $installRoot = sprintf("__DIR__ . '/%s'", $installRoot);
        }

        return <<<TEMPLATE
        <?php

        /**
         * Include the Composer autoload file for a Composer-based Moodle installation.
         *
         * This file was automatically generated by the Moodle Composer Scaffold plugin.
         *
         * Do NOT edit this file manually. It will be overridden on the next scaffolding operation.
         */

        \$installRoot = {$installRoot};
        return require_once(\$installRoot . '/vendor/autoload.php');

        TEMPLATE;
    }
}
