<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace Moodle\Composer\Scaffold\Scaffolding\Generator;

/**
 * Moodle Config File Generator.
 */
class ShimConfigFile extends BaseGenerator
{
    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function generate(): void
    {
        $this->io->write("- <info>Generating Moodle configuration shim file...</info>", false);

        $targetPath = $this->getMoodlePath() . '/config.php';

        file_put_contents($targetPath, $this->getTemplateContent());

        $this->io->write("<info> done.</info>");
    }

    protected function getTemplateContent(): string
    {
        $vendorPath = $this->getVendorPath();
        $generatedConfigPath = $this->getMoodlePath() . '/config.php';

        $relativeConfigPath = $this->calculateRelativePath(
            $generatedConfigPath,
            dirname($vendorPath) . '/config.php',
        );

        $composerAutoloadPath = $this->getVendorPath() . '/autoload.php';
        $relativeAutoloadPath = $this->calculateRelativePath(
            $generatedConfigPath,
            $composerAutoloadPath,
        );

        return <<<TEMPLATE
        <?php

        /**
         * Include the Moodle configuration file for a Composer-based Moodle installation.
         *
         * This file was automatically generated by the Moodle Composer Scaffold plugin.
         *
         * Do NOT edit this file manually. It will be overridden on the next scaffolding operation.
         */
        \$result = require_once(__DIR__ . '/{$relativeConfigPath}');
        require_once(__DIR__ . '/{$relativeAutoloadPath}');
        require_once(__DIR__ . '/public/lib/setup.php');

        return \$result;

        TEMPLATE;
    }
}
